name    'puppet-forumone'
version '1.1.35'
source ''
author 'William Hurley'
license 'GPL v2'
summary 'Forum One puppet module for development'
description 'Creates an idiosyncratic development environment for PHP or Javascript development'
project_page ''

## Add dependencies, if any:
dependency 'puppetlabs/apache', '1.0.1'
dependency 'puppetlabs/apt', '1.1.x'
dependency 'puppetlabs/concat', '1.0.x'
dependency 'puppetlabs/ruby', '0.4.x'
dependency 'stahnma/epel', '0.0.5'
dependency 'puppetlabs/firewall', '0.4.x'
dependency 'thias/memcached', '0.1.x'
dependency 'fsalum/redis', '0.0.11'
dependency 'puppetlabs/nodejs', '0.4.x'
dependency 'thias/php', '0.3.x'
dependency 'alup/rbenv', '1.2.x'
