name    'puppet-forumone'
version '1.1.3'
source ''
author 'William Hurley'
license 'GPL v2'
summary 'Forum One puppet module for development'
description 'Creates an idiosyncratic development environment for PHP or Javascript development'
project_page ''

## Add dependencies, if any:
dependency 'puppetlabs/apache', '~>0.9'
dependency 'puppetlabs/apt', '~>1.1'
dependency 'puppetlabs/concat', '~>1.0'
dependency 'stahnma/epel', '0.0.5'
dependency 'puppetlabs/firewall', '~>0.4'
dependency 'thias/memcached', '~>0.1'
dependency 'fsalum/redis', '~>0.0.9'
